export type Difficulty = "简单" | "中等" | "困难";

export interface ProblemTest {
  expression: string;
  expected: unknown;
  inputLabel: string;
}

export interface Problem {
  id: number;
  title: string;
  slug: string;
  topic: string;
  difficulty: Difficulty;
  summary: string;
  example: string;
  method: string;
  params: string[];
  hint: string;
  complexity: string;
  starterCode: string;
  tests: ProblemTest[];
}

type Seed = Omit<Problem, "starterCode"> & {
  functionName?: string;
  starterCode?: string;
};

const starter = (functionName: string, params: string[]) =>
  `class Solution:\n    def ${functionName}(self, ${params.join(", ")}):\n        # 写下你的解法\n        pass`;

const q = (seed: Seed): Problem => ({
  ...seed,
  starterCode:
    seed.starterCode ?? starter(seed.functionName ?? seed.slug.replace(/-/g, "_"), seed.params),
});

const t = (inputLabel: string, expression: string, expected: unknown): ProblemTest => ({
  inputLabel,
  expression,
  expected,
});

/**
 * LeetCode 经典 Hot 100。
 * 链表、树和原地修改题的表达式依赖运行器提供的 build_list、list_values、
 * build_tree、tree_values、mutated 等轻量夹具；设计题统一使用 run_operations。
 */
export const problems: Problem[] = [
  q({ id: 1, title: "两数之和", slug: "two-sum", topic: "哈希", difficulty: "简单",
    summary: "在数组中找到和为目标值的两个数，并返回它们的下标。", example: "nums = [2,7,11,15], target = 9 → [0,1]",
    method: "遍历数组，用哈希表保存已经见过的数字及其下标。", params: ["nums", "target"],
    hint: "当前数字是 num 时，需要的另一个数是 target - num。", complexity: "时间 O(n)，空间 O(n)", functionName: "twoSum",
    tests: [t("[2,7,11,15], target=9", "sorted(twoSum([2,7,11,15], 9))", [0,1]), t("[3,2,4], target=6", "sorted(twoSum([3,2,4], 6))", [1,2])] }),
  q({ id: 49, title: "字母异位词分组", slug: "group-anagrams", topic: "哈希", difficulty: "中等",
    summary: "把由相同字母重新排列而成的字符串放进同一组。", example: "[eat, tea, tan, ate, nat, bat] → 3 组",
    method: "把排序后的字符串当作哈希键，原字符串加入对应分组。", params: ["strs"],
    hint: "异位词排序后完全相同。", complexity: "时间 O(n·k log k)，空间 O(nk)", functionName: "groupAnagrams",
    tests: [t("六个单词", "sorted([sorted(g) for g in groupAnagrams(['eat','tea','tan','ate','nat','bat'])])", [["ate","eat","tea"],["bat"],["nat","tan"]]), t("单个空串", "groupAnagrams([''])", [[""]])] }),
  q({ id: 128, title: "最长连续序列", slug: "longest-consecutive-sequence", topic: "哈希", difficulty: "中等",
    summary: "求未排序数组中最长连续整数序列的长度。", example: "[100,4,200,1,3,2] → 4",
    method: "用集合去重，只从没有前驱的数字开始向后扩展。", params: ["nums"],
    hint: "若 x-1 存在，x 就不是一段序列的起点。", complexity: "平均时间 O(n)，空间 O(n)", functionName: "longestConsecutive",
    tests: [t("包含 1~4", "longestConsecutive([100,4,200,1,3,2])", 4), t("含重复数字", "longestConsecutive([0,3,7,2,5,8,4,6,0,1])", 9)] }),
  q({ id: 283, title: "移动零", slug: "move-zeroes", topic: "双指针", difficulty: "简单",
    summary: "原地把所有零移到数组末尾，同时保持非零元素顺序。", example: "[0,1,0,3,12] → [1,3,12,0,0]",
    method: "慢指针指向下一个非零写入位置，最后补零。", params: ["nums"],
    hint: "先稳定压缩非零数字。", complexity: "时间 O(n)，空间 O(1)", functionName: "moveZeroes",
    tests: [t("两个零", "mutated([0,1,0,3,12], moveZeroes)", [1,3,12,0,0]), t("只有一个零", "mutated([0], moveZeroes)", [0])] }),
  q({ id: 11, title: "盛最多水的容器", slug: "container-with-most-water", topic: "双指针", difficulty: "中等",
    summary: "选择两条竖线，使它们与横轴围成的容器面积最大。", example: "[1,8,6,2,5,4,8,3,7] → 49",
    method: "左右指针计算面积，每次移动较短的一边。", params: ["height"],
    hint: "移动长边不会突破当前短边造成的高度上限。", complexity: "时间 O(n)，空间 O(1)", functionName: "maxArea",
    tests: [t("经典示例", "maxArea([1,8,6,2,5,4,8,3,7])", 49), t("两条线", "maxArea([1,1])", 1)] }),
  q({ id: 15, title: "三数之和", slug: "3sum", topic: "双指针", difficulty: "中等",
    summary: "找出数组中所有和为零且不重复的三元组。", example: "[-1,0,1,2,-1,-4] → [[-1,-1,2],[-1,0,1]]",
    method: "先排序，枚举第一个数，再用左右指针寻找另外两个数。", params: ["nums"],
    hint: "排序后可以跳过重复值，并根据当前和移动指针。", complexity: "时间 O(n²)，空间 O(1)（不计结果）", functionName: "threeSum",
    tests: [t("两个答案", "sorted([sorted(x) for x in threeSum([-1,0,1,2,-1,-4])])", [[-1,-1,2],[-1,0,1]]), t("无解", "threeSum([0,1,1])", [])] }),
  q({ id: 167, title: "两数之和 II - 输入有序数组", slug: "two-sum-ii-input-array-is-sorted", topic: "双指针", difficulty: "中等",
    summary: "在一个按非递减顺序排列的数组中，找到和为目标值的两个数，并返回它们从 1 开始计算的位置。", example: "numbers = [2,7,11,15], target = 9 → [1,2]",
    method: "用左右指针夹逼：和偏小时左指针右移，和偏大时右指针左移。", params: ["numbers", "target"],
    hint: "数组已经有序；找到答案后要返回 [left + 1, right + 1]。", complexity: "时间 O(n)，空间 O(1)", functionName: "twoSum",
    tests: [t("首尾之间找到答案", "twoSum([2,7,11,15], 9)", [1,2]), t("答案跨过中间元素", "twoSum([2,3,4], 6)", [1,3]), t("包含负数", "twoSum([-1,0], -1)", [1,2])] }),
  q({ id: 42, title: "接雨水", slug: "trapping-rain-water", topic: "双指针", difficulty: "困难",
    summary: "根据柱子高度，计算下雨后能够接住的总水量。", example: "[0,1,0,2,1,0,1,3,2,1,2,1] → 6",
    method: "维护左右最高柱，较低一侧可以立即确定当前积水。", params: ["height"],
    hint: "某格水位由左右最高值中较小的那个决定。", complexity: "时间 O(n)，空间 O(1)", functionName: "trap",
    tests: [t("经典示例", "trap([0,1,0,2,1,0,1,3,2,1,2,1])", 6), t("另一组柱子", "trap([4,2,0,3,2,5])", 9)] }),
  q({ id: 3, title: "无重复字符的最长子串", slug: "longest-substring-without-repeating-characters", topic: "滑动窗口", difficulty: "中等",
    summary: "求字符串中不含重复字符的最长连续片段长度。", example: "abcabcbb → 3",
    method: "右指针扩展窗口，发现重复时移动左边界。", params: ["s"],
    hint: "记录每个字符最近出现的位置，可以一次跳过冲突。", complexity: "时间 O(n)，空间 O(k)", functionName: "lengthOfLongestSubstring",
    tests: [t("重复循环", "lengthOfLongestSubstring('abcabcbb')", 3), t("全部相同", "lengthOfLongestSubstring('bbbbb')", 1)] }),
  q({ id: 438, title: "找到字符串中所有字母异位词", slug: "find-all-anagrams-in-a-string", topic: "滑动窗口", difficulty: "中等",
    summary: "找出字符串 s 中所有与 p 互为异位词的子串起点。", example: "s=cbaebabacd, p=abc → [0,6]",
    method: "维护长度固定为 p 的窗口，并比较字符计数。", params: ["s", "p"],
    hint: "窗口每右移一步，只需减去离开的字符、加上进入的字符。", complexity: "时间 O(n)，空间 O(字符集)", functionName: "findAnagrams",
    tests: [t("两个起点", "findAnagrams('cbaebabacd', 'abc')", [0,6]), t("重叠答案", "findAnagrams('abab', 'ab')", [0,1,2])] }),
  q({ id: 560, title: "和为 K 的子数组", slug: "subarray-sum-equals-k", topic: "子串", difficulty: "中等",
    summary: "统计和恰好为 k 的连续子数组个数。", example: "nums=[1,1,1], k=2 → 2",
    method: "用前缀和与哈希表统计此前出现过多少个 prefix-k。", params: ["nums", "k"],
    hint: "区间和为 k 等价于两个前缀和相差 k。", complexity: "时间 O(n)，空间 O(n)", functionName: "subarraySum",
    tests: [t("三个 1", "subarraySum([1,1,1], 2)", 2), t("不同长度", "subarraySum([1,2,3], 3)", 2)] }),
  q({ id: 239, title: "滑动窗口最大值", slug: "sliding-window-maximum", topic: "子串", difficulty: "困难",
    summary: "返回每个长度为 k 的滑动窗口中的最大值。", example: "[1,3,-1,-3,5,3,6,7], k=3 → [3,3,5,5,6,7]",
    method: "用单调递减双端队列保存仍可能成为最大值的下标。", params: ["nums", "k"],
    hint: "新元素进入时，队尾比它小的元素以后都不会成为答案。", complexity: "时间 O(n)，空间 O(k)", functionName: "maxSlidingWindow",
    tests: [t("窗口 3", "maxSlidingWindow([1,3,-1,-3,5,3,6,7], 3)", [3,3,5,5,6,7]), t("单元素", "maxSlidingWindow([1], 1)", [1])] }),
  q({ id: 76, title: "最小覆盖子串", slug: "minimum-window-substring", topic: "子串", difficulty: "困难",
    summary: "在 s 中寻找包含 t 全部字符的最短连续子串。", example: "s=ADOBECODEBANC, t=ABC → BANC",
    method: "扩张窗口直到满足需求，再收缩左端寻找最短答案。", params: ["s", "t"],
    hint: "用 missing 或满足计数判断窗口何时完整覆盖。", complexity: "时间 O(|s|+|t|)，空间 O(字符集)", functionName: "minWindow",
    tests: [t("经典示例", "minWindow('ADOBECODEBANC', 'ABC')", "BANC"), t("完全相同", "minWindow('a', 'a')", "a")] }),
  q({ id: 53, title: "最大子数组和", slug: "maximum-subarray", topic: "普通数组", difficulty: "中等",
    summary: "找出和最大的非空连续子数组，并返回其和。", example: "[-2,1,-3,4,-1,2,1,-5,4] → 6",
    method: "当前位置的最优和，要么从当前数重新开始，要么接在前一段后面。", params: ["nums"],
    hint: "若之前的累计和为负，继续携带只会变差。", complexity: "时间 O(n)，空间 O(1)", functionName: "maxSubArray",
    tests: [t("中间最佳", "maxSubArray([-2,1,-3,4,-1,2,1,-5,4])", 6), t("单个负数", "maxSubArray([-1])", -1)] }),
  q({ id: 56, title: "合并区间", slug: "merge-intervals", topic: "普通数组", difficulty: "中等",
    summary: "把所有相互重叠的区间合并。", example: "[[1,3],[2,6],[8,10],[15,18]] → [[1,6],[8,10],[15,18]]",
    method: "按起点排序，逐个与结果中的最后一个区间比较。", params: ["intervals"],
    hint: "当前起点不大于上一段终点时，两段可以合并。", complexity: "时间 O(n log n)，空间 O(n)", functionName: "merge",
    tests: [t("一处重叠", "merge([[1,3],[2,6],[8,10],[15,18]])", [[1,6],[8,10],[15,18]]), t("首尾相接", "merge([[1,4],[4,5]])", [[1,5]])] }),
  q({ id: 189, title: "轮转数组", slug: "rotate-array", topic: "普通数组", difficulty: "中等",
    summary: "将数组原地向右轮转 k 个位置。", example: "[1,2,3,4,5,6,7], k=3 → [5,6,7,1,2,3,4]",
    method: "整体反转，再分别反转前 k 个和剩余部分。", params: ["nums", "k"],
    hint: "先令 k %= n，避免无效整圈。", complexity: "时间 O(n)，空间 O(1)", functionName: "rotate",
    tests: [t("右移 3 位", "mutated([1,2,3,4,5,6,7], rotate, 3)", [5,6,7,1,2,3,4]), t("含负数", "mutated([-1,-100,3,99], rotate, 2)", [3,99,-1,-100])] }),
  q({ id: 238, title: "除自身以外数组的乘积", slug: "product-of-array-except-self", topic: "普通数组", difficulty: "中等",
    summary: "不使用除法，返回每个位置之外所有数字的乘积。", example: "[1,2,3,4] → [24,12,8,6]",
    method: "先写入左侧乘积，再从右向左乘上右侧乘积。", params: ["nums"],
    hint: "答案可以同时充当前缀积数组。", complexity: "时间 O(n)，额外空间 O(1)", functionName: "productExceptSelf",
    tests: [t("正整数", "productExceptSelf([1,2,3,4])", [24,12,8,6]), t("含两个零", "productExceptSelf([-1,1,0,-3,3])", [0,0,9,0,0])] }),
  q({ id: 41, title: "缺失的第一个正数", slug: "first-missing-positive", topic: "普通数组", difficulty: "困难",
    summary: "在线性时间和常数额外空间内找到最小缺失正整数。", example: "[3,4,-1,1] → 2",
    method: "把 1..n 中的值交换到下标 value-1 的位置，再扫描错位处。", params: ["nums"],
    hint: "长度为 n 的数组，答案一定落在 1..n+1。", complexity: "时间 O(n)，空间 O(1)", functionName: "firstMissingPositive",
    tests: [t("缺少 2", "firstMissingPositive([3,4,-1,1])", 2), t("缺少 3", "firstMissingPositive([1,2,0])", 3)] }),
  q({ id: 73, title: "矩阵置零", slug: "set-matrix-zeroes", topic: "矩阵", difficulty: "中等",
    summary: "若矩阵某格为零，将它所在的整行和整列都设为零。", example: "[[1,1,1],[1,0,1],[1,1,1]] → 中间十字置零",
    method: "用第一行和第一列充当标记，并单独记录它们原先是否含零。", params: ["matrix"],
    hint: "不要在第一次扫描时立刻扩散零。", complexity: "时间 O(mn)，空间 O(1)", functionName: "setZeroes",
    tests: [t("中心为零", "mutated([[1,1,1],[1,0,1],[1,1,1]], setZeroes)", [[1,0,1],[0,0,0],[1,0,1]]), t("首行含零", "mutated([[0,1],[1,1]], setZeroes)", [[0,0],[0,1]])] }),
  q({ id: 54, title: "螺旋矩阵", slug: "spiral-matrix", topic: "矩阵", difficulty: "中等",
    summary: "按顺时针螺旋顺序返回矩阵中的所有元素。", example: "[[1,2,3],[4,5,6],[7,8,9]] → [1,2,3,6,9,8,7,4,5]",
    method: "维护上下左右四条边界，每走完一边就向内收缩。", params: ["matrix"],
    hint: "走下边和左边前再次检查边界是否仍有效。", complexity: "时间 O(mn)，空间 O(1)（不计结果）", functionName: "spiralOrder",
    tests: [t("3×3", "spiralOrder([[1,2,3],[4,5,6],[7,8,9]])", [1,2,3,6,9,8,7,4,5]), t("2×3", "spiralOrder([[1,2,3],[4,5,6]])", [1,2,3,6,5,4])] }),
  q({ id: 48, title: "旋转图像", slug: "rotate-image", topic: "矩阵", difficulty: "中等",
    summary: "将 n×n 矩阵原地顺时针旋转 90 度。", example: "[[1,2,3],[4,5,6],[7,8,9]] → [[7,4,1],[8,5,2],[9,6,3]]",
    method: "先沿主对角线转置，再反转每一行。", params: ["matrix"],
    hint: "顺时针旋转可以拆成转置加水平翻转。", complexity: "时间 O(n²)，空间 O(1)", functionName: "rotate",
    tests: [t("3×3", "mutated([[1,2,3],[4,5,6],[7,8,9]], rotate)", [[7,4,1],[8,5,2],[9,6,3]]), t("2×2", "mutated([[1,2],[3,4]], rotate)", [[3,1],[4,2]])] }),
  q({ id: 240, title: "搜索二维矩阵 II", slug: "search-a-2d-matrix-ii", topic: "矩阵", difficulty: "中等",
    summary: "在行列都递增的矩阵中判断目标值是否存在。", example: "target=5 → true",
    method: "从右上角开始：过大向左，过小向下。", params: ["matrix", "target"],
    hint: "右上角同时拥有一个可排除的行方向和列方向。", complexity: "时间 O(m+n)，空间 O(1)", functionName: "searchMatrix",
    tests: [t("找到 5", "searchMatrix([[1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]], 5)", true), t("找不到 20", "searchMatrix([[1,4,7],[2,5,8],[3,6,9]], 20)", false)] }),
  q({ id: 160, title: "相交链表", slug: "intersection-of-two-linked-lists", topic: "链表", difficulty: "简单",
    summary: "找出两条单链表开始相交的节点；不相交则返回空。", example: "A=[4,1]+[8,4,5], B=[5,6,1]+[8,4,5] → 8",
    method: "两个指针走到末尾后切换到另一条链表，路程会被补齐。", params: ["headA", "headB"],
    hint: "A+B 与 B+A 的总长度相同。", complexity: "时间 O(m+n)，空间 O(1)", functionName: "getIntersectionNode",
    tests: [t("在值 8 处相交", "node_value(getIntersectionNode(*build_intersecting_lists([4,1],[5,6,1],[8,4,5])))", 8), t("不相交", "getIntersectionNode(build_list([2,6,4]), build_list([1,5])) is None", true)] }),
  q({ id: 206, title: "反转链表", slug: "reverse-linked-list", topic: "链表", difficulty: "简单",
    summary: "反转一条单链表并返回新的头节点。", example: "1→2→3→4→5 → 5→4→3→2→1",
    method: "依次保存 next，令当前节点指向 prev，再推进两个指针。", params: ["head"],
    hint: "改指针前先保存原来的下一个节点。", complexity: "时间 O(n)，空间 O(1)", functionName: "reverseList",
    tests: [t("五个节点", "list_values(reverseList(build_list([1,2,3,4,5])))", [5,4,3,2,1]), t("单节点", "list_values(reverseList(build_list([1])))", [1])] }),
  q({ id: 234, title: "回文链表", slug: "palindrome-linked-list", topic: "链表", difficulty: "简单",
    summary: "判断单链表从前向后与从后向前读是否相同。", example: "1→2→2→1 → true",
    method: "快慢指针找中点，反转后半段，再逐一比较。", params: ["head"],
    hint: "快指针每次走两步，慢指针会停在中间。", complexity: "时间 O(n)，空间 O(1)", functionName: "isPalindrome",
    tests: [t("偶数回文", "isPalindrome(build_list([1,2,2,1]))", true), t("不是回文", "isPalindrome(build_list([1,2]))", false)] }),
  q({ id: 141, title: "环形链表", slug: "linked-list-cycle", topic: "链表", difficulty: "简单",
    summary: "判断链表中是否存在沿 next 指针可重复进入的环。", example: "[3,2,0,-4], 尾部连到下标 1 → true",
    method: "快慢指针同时出发，有环时快指针最终会追上慢指针。", params: ["head"],
    hint: "慢指针走一步，快指针走两步。", complexity: "时间 O(n)，空间 O(1)", functionName: "hasCycle",
    tests: [t("尾部连回下标 1", "hasCycle(build_cycle_list([3,2,0,-4], 1))", true), t("没有环", "hasCycle(build_list([1,2]))", false)] }),
  q({ id: 142, title: "环形链表 II", slug: "linked-list-cycle-ii", topic: "链表", difficulty: "中等",
    summary: "若链表有环，返回环开始的节点；否则返回空。", example: "[3,2,0,-4], 尾部连到下标 1 → 节点 2",
    method: "快慢指针相遇后，一个指针回到头部，再同步前进，相遇点就是入口。", params: ["head"],
    hint: "利用相遇时的路程关系消去绕环圈数。", complexity: "时间 O(n)，空间 O(1)", functionName: "detectCycle",
    tests: [t("入口值为 2", "node_value(detectCycle(build_cycle_list([3,2,0,-4], 1)))", 2), t("没有环", "detectCycle(build_list([1,2])) is None", true)] }),
  q({ id: 21, title: "合并两个有序链表", slug: "merge-two-sorted-lists", topic: "链表", difficulty: "简单",
    summary: "把两条升序链表合并成一条升序链表。", example: "[1,2,4] + [1,3,4] → [1,1,2,3,4,4]",
    method: "用哑节点串起每次较小的节点，最后接上剩余部分。", params: ["list1", "list2"],
    hint: "哑节点能免去单独处理头节点。", complexity: "时间 O(m+n)，空间 O(1)", functionName: "mergeTwoLists",
    tests: [t("两条非空链表", "list_values(mergeTwoLists(build_list([1,2,4]), build_list([1,3,4])))", [1,1,2,3,4,4]), t("两条空链表", "list_values(mergeTwoLists(None, None))", [])] }),
  q({ id: 2, title: "两数相加", slug: "add-two-numbers", topic: "链表", difficulty: "中等",
    summary: "两条链表按低位到高位保存整数，返回它们的和。", example: "[2,4,3] + [5,6,4] → [7,0,8]",
    method: "同步遍历两条链表，逐位相加并维护进位。", params: ["l1", "l2"],
    hint: "循环条件还要包含 carry，最后可能多一位。", complexity: "时间 O(max(m,n))，空间 O(max(m,n))", functionName: "addTwoNumbers",
    tests: [t("342 + 465", "list_values(addTwoNumbers(build_list([2,4,3]), build_list([5,6,4])))", [7,0,8]), t("0 + 0", "list_values(addTwoNumbers(build_list([0]), build_list([0])))", [0])] }),
  q({ id: 19, title: "删除链表的倒数第 N 个结点", slug: "remove-nth-node-from-end-of-list", topic: "链表", difficulty: "中等",
    summary: "删除链表倒数第 n 个节点，并返回头节点。", example: "[1,2,3,4,5], n=2 → [1,2,3,5]",
    method: "快指针先走 n 步，再让快慢指针同步移动。", params: ["head", "n"],
    hint: "从哑节点出发可以统一删除头节点的情况。", complexity: "时间 O(n)，空间 O(1)", functionName: "removeNthFromEnd",
    tests: [t("删除倒数第二个", "list_values(removeNthFromEnd(build_list([1,2,3,4,5]), 2))", [1,2,3,5]), t("删除唯一节点", "list_values(removeNthFromEnd(build_list([1]), 1))", [])] }),
  q({ id: 24, title: "两两交换链表中的节点", slug: "swap-nodes-in-pairs", topic: "链表", difficulty: "中等",
    summary: "不修改节点值，每两个相邻节点交换位置。", example: "[1,2,3,4] → [2,1,4,3]",
    method: "从哑节点开始，每次重连一对节点的三条边。", params: ["head"],
    hint: "先保存 pair 后面的节点，避免断链。", complexity: "时间 O(n)，空间 O(1)", functionName: "swapPairs",
    tests: [t("四个节点", "list_values(swapPairs(build_list([1,2,3,4])))", [2,1,4,3]), t("三个节点", "list_values(swapPairs(build_list([1,2,3])))", [2,1,3])] }),
  q({ id: 25, title: "K 个一组翻转链表", slug: "reverse-nodes-in-k-group", topic: "链表", difficulty: "困难",
    summary: "每 k 个节点为一组翻转链表，不足 k 个的尾部保持原样。", example: "[1,2,3,4,5], k=2 → [2,1,4,3,5]",
    method: "先检查一组是否够 k 个，再局部反转并把组间重新接好。", params: ["head", "k"],
    hint: "记录上一组尾、当前组头和下一组头。", complexity: "时间 O(n)，空间 O(1)", functionName: "reverseKGroup",
    tests: [t("每 2 个翻转", "list_values(reverseKGroup(build_list([1,2,3,4,5]), 2))", [2,1,4,3,5]), t("每 3 个翻转", "list_values(reverseKGroup(build_list([1,2,3,4,5]), 3))", [3,2,1,4,5])] }),
  q({ id: 138, title: "随机链表的复制", slug: "copy-list-with-random-pointer", topic: "链表", difficulty: "中等",
    summary: "深拷贝一条每个节点还带 random 指针的链表。", example: "[[7,null],[13,0],[11,4],[10,2],[1,0]] → 独立同构链表",
    method: "用哈希表记录旧节点到新节点，再补齐 next 与 random。", params: ["head"],
    hint: "不要让新链表中的任何指针指回旧节点。", complexity: "时间 O(n)，空间 O(n)", functionName: "copyRandomList",
    tests: [t("五个随机节点", "random_list_values(copyRandomList(build_random_list([[7,None],[13,0],[11,4],[10,2],[1,0]])))", [[7,null],[13,0],[11,4],[10,2],[1,0]]), t("空链表", "copyRandomList(None) is None", true)] }),
  q({ id: 148, title: "排序链表", slug: "sort-list", topic: "链表", difficulty: "中等",
    summary: "在 O(n log n) 时间内把链表按升序排列。", example: "[4,2,1,3] → [1,2,3,4]",
    method: "用归并排序：快慢指针拆分，递归排序后合并。", params: ["head"],
    hint: "链表不适合随机访问，但合并两个有序链表很高效。", complexity: "时间 O(n log n)，递归空间 O(log n)", functionName: "sortList",
    tests: [t("四个节点", "list_values(sortList(build_list([4,2,1,3])))", [1,2,3,4]), t("含负数", "list_values(sortList(build_list([-1,5,3,4,0])))", [-1,0,3,4,5])] }),
  q({ id: 23, title: "合并 K 个升序链表", slug: "merge-k-sorted-lists", topic: "链表", difficulty: "困难",
    summary: "把 k 条升序链表合并为一条升序链表。", example: "[[1,4,5],[1,3,4],[2,6]] → [1,1,2,3,4,4,5,6]",
    method: "把每条链表头放入最小堆，每弹出一个节点就加入它的后继。", params: ["lists"],
    hint: "堆中最多只有 k 个候选节点。", complexity: "时间 O(n log k)，空间 O(k)", functionName: "mergeKLists",
    tests: [t("三条链表", "list_values(mergeKLists([build_list([1,4,5]),build_list([1,3,4]),build_list([2,6])]))", [1,1,2,3,4,4,5,6]), t("空列表", "list_values(mergeKLists([]))", [])] }),
  q({ id: 146, title: "LRU 缓存", slug: "lru-cache", topic: "链表", difficulty: "中等",
    summary: "实现固定容量缓存，读取和写入都要在 O(1) 内完成，并淘汰最久未使用项。", example: "容量 2，连续 put/get 后按最近使用顺序淘汰",
    method: "哈希表负责定位，双向链表维护最近使用顺序。", params: ["capacity"],
    hint: "访问节点后要把它移到链表的最近使用端。", complexity: "get/put 平均 O(1)，空间 O(capacity)",
    starterCode: `class LRUCache:
    def __init__(self, capacity):
        self.capacity = capacity
        # 在这里初始化哈希表与双向链表

    def get(self, key):
        pass

    def put(self, key, value):
        pass`,
    tests: [t("容量 2 的标准流程", "run_operations(LRUCache, ['LRUCache','put','put','get','put','get','put','get','get','get'], [[2],[1,1],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]])", [null,null,null,1,null,-1,null,-1,3,4])] }),
  q({ id: 94, title: "二叉树的中序遍历", slug: "binary-tree-inorder-traversal", topic: "二叉树", difficulty: "简单",
    summary: "按左子树、根节点、右子树的顺序返回所有节点值。", example: "[1,null,2,3] → [1,3,2]",
    method: "用栈一路压入左节点，弹出访问后转向右子树。", params: ["root"],
    hint: "当前节点为空时，应该从栈顶回退。", complexity: "时间 O(n)，空间 O(h)", functionName: "inorderTraversal",
    tests: [t("右子树带左孩子", "inorderTraversal(build_tree([1,None,2,3]))", [1,3,2]), t("空树", "inorderTraversal(None)", [])] }),
  q({ id: 104, title: "二叉树的最大深度", slug: "maximum-depth-of-binary-tree", topic: "二叉树", difficulty: "简单",
    summary: "返回根节点到最远叶子节点所经过的节点数。", example: "[3,9,20,null,null,15,7] → 3",
    method: "递归求左右子树深度，取较大值再加一。", params: ["root"],
    hint: "空树深度为 0。", complexity: "时间 O(n)，空间 O(h)", functionName: "maxDepth",
    tests: [t("三层树", "maxDepth(build_tree([3,9,20,None,None,15,7]))", 3), t("只有右孩子", "maxDepth(build_tree([1,None,2]))", 2)] }),
  q({ id: 226, title: "翻转二叉树", slug: "invert-binary-tree", topic: "二叉树", difficulty: "简单",
    summary: "交换二叉树中每个节点的左右子树。", example: "[4,2,7,1,3,6,9] → [4,7,2,9,6,3,1]",
    method: "递归翻转左右子树，再交换它们。", params: ["root"],
    hint: "每个节点都做同一件事：交换左右孩子。", complexity: "时间 O(n)，空间 O(h)", functionName: "invertTree",
    tests: [t("完整三层", "tree_values(invertTree(build_tree([4,2,7,1,3,6,9])))", [4,7,2,9,6,3,1]), t("空树", "tree_values(invertTree(None))", [])] }),
  q({ id: 101, title: "对称二叉树", slug: "symmetric-tree", topic: "二叉树", difficulty: "简单",
    summary: "判断二叉树是否以根节点为轴镜像对称。", example: "[1,2,2,3,4,4,3] → true",
    method: "成对比较左树的左/右与右树的右/左。", params: ["root"],
    hint: "比较的是镜像位置，而不是相同方向。", complexity: "时间 O(n)，空间 O(h)", functionName: "isSymmetric",
    tests: [t("对称", "isSymmetric(build_tree([1,2,2,3,4,4,3]))", true), t("不对称", "isSymmetric(build_tree([1,2,2,None,3,None,3]))", false)] }),
  q({ id: 543, title: "二叉树的直径", slug: "diameter-of-binary-tree", topic: "二叉树", difficulty: "简单",
    summary: "求树中任意两节点之间最长路径包含的边数。", example: "[1,2,3,4,5] → 3",
    method: "后序求每个节点的左右深度，用左右深度之和更新答案。", params: ["root"],
    hint: "最长路径不一定经过根节点。", complexity: "时间 O(n)，空间 O(h)", functionName: "diameterOfBinaryTree",
    tests: [t("最长路径 4-2-1-3", "diameterOfBinaryTree(build_tree([1,2,3,4,5]))", 3), t("两个节点", "diameterOfBinaryTree(build_tree([1,2]))", 1)] }),
  q({ id: 102, title: "二叉树的层序遍历", slug: "binary-tree-level-order-traversal", topic: "二叉树", difficulty: "中等",
    summary: "从上到下逐层返回二叉树节点值。", example: "[3,9,20,null,null,15,7] → [[3],[9,20],[15,7]]",
    method: "用队列做广度优先搜索，每轮固定处理当前队列长度。", params: ["root"],
    hint: "一轮开始时的队列长度就是这一层节点数。", complexity: "时间 O(n)，空间 O(w)", functionName: "levelOrder",
    tests: [t("三层树", "levelOrder(build_tree([3,9,20,None,None,15,7]))", [[3],[9,20],[15,7]]), t("空树", "levelOrder(None)", [])] }),
  q({ id: 108, title: "将有序数组转换为二叉搜索树", slug: "convert-sorted-array-to-binary-search-tree", topic: "二叉树", difficulty: "简单",
    summary: "把升序数组转换为高度平衡的二叉搜索树。", example: "[-10,-3,0,5,9] → 一棵平衡 BST",
    method: "每次取区间中点作根，递归构造左右半区。", params: ["nums"],
    hint: "中点能让左右子树节点数尽量接近。", complexity: "时间 O(n)，空间 O(log n)", functionName: "sortedArrayToBST",
    tests: [t("五个有序数字", "is_height_balanced(sortedArrayToBST([-10,-3,0,5,9])) and inorder_values(sortedArrayToBST([-10,-3,0,5,9])) == [-10,-3,0,5,9]", true), t("两个数字", "inorder_values(sortedArrayToBST([1,3]))", [1,3])] }),
  q({ id: 98, title: "验证二叉搜索树", slug: "validate-binary-search-tree", topic: "二叉树", difficulty: "中等",
    summary: "判断二叉树是否满足每个节点左侧都更小、右侧都更大。", example: "[2,1,3] → true",
    method: "递归传递当前节点允许的开区间上下界。", params: ["root"],
    hint: "不能只比较父子节点；祖先也会限制取值。", complexity: "时间 O(n)，空间 O(h)", functionName: "isValidBST",
    tests: [t("合法 BST", "isValidBST(build_tree([2,1,3]))", true), t("右子树含过小值", "isValidBST(build_tree([5,1,4,None,None,3,6]))", false)] }),
  q({ id: 230, title: "二叉搜索树中第 K 小的元素", slug: "kth-smallest-element-in-a-bst", topic: "二叉树", difficulty: "中等",
    summary: "返回二叉搜索树中按值排序后的第 k 小元素。", example: "[3,1,4,null,2], k=1 → 1",
    method: "BST 的中序遍历是升序，访问到第 k 个即可返回。", params: ["root", "k"],
    hint: "不必把全部中序结果都存下来。", complexity: "时间 O(h+k)，空间 O(h)", functionName: "kthSmallest",
    tests: [t("第 1 小", "kthSmallest(build_tree([3,1,4,None,2]), 1)", 1), t("第 3 小", "kthSmallest(build_tree([5,3,6,2,4,None,None,1]), 3)", 3)] }),
  q({ id: 199, title: "二叉树的右视图", slug: "binary-tree-right-side-view", topic: "二叉树", difficulty: "中等",
    summary: "返回从树的右侧能看到的每一层节点值。", example: "[1,2,3,null,5,null,4] → [1,3,4]",
    method: "层序遍历时记录每层最后一个节点。", params: ["root"],
    hint: "也可先右后左 DFS，首次到达某层时记录。", complexity: "时间 O(n)，空间 O(w)", functionName: "rightSideView",
    tests: [t("三层树", "rightSideView(build_tree([1,2,3,None,5,None,4]))", [1,3,4]), t("只有右支", "rightSideView(build_tree([1,None,3]))", [1,3])] }),
  q({ id: 114, title: "二叉树展开为链表", slug: "flatten-binary-tree-to-linked-list", topic: "二叉树", difficulty: "中等",
    summary: "原地把二叉树按前序遍历顺序展开成只含右指针的链。", example: "[1,2,5,3,4,null,6] → 1→2→3→4→5→6",
    method: "从后向前处理前序序列，让当前节点右指针指向上一个已处理节点。", params: ["root"],
    hint: "反向顺序是右、左、根。", complexity: "时间 O(n)，空间 O(h)", functionName: "flatten",
    tests: [t("标准树", "flattened_values(build_tree([1,2,5,3,4,None,6]), flatten)", [1,2,3,4,5,6]), t("空树", "flattened_values(None, flatten)", [])] }),
  q({ id: 105, title: "从前序与中序遍历序列构造二叉树", slug: "construct-binary-tree-from-preorder-and-inorder-traversal", topic: "二叉树", difficulty: "中等",
    summary: "根据无重复值的前序和中序序列还原二叉树。", example: "pre=[3,9,20,15,7], in=[9,3,15,20,7]",
    method: "前序首项是根，在中序中定位根后递归切分左右子树。", params: ["preorder", "inorder"],
    hint: "用哈希表预存中序下标，避免重复查找。", complexity: "时间 O(n)，空间 O(n)", functionName: "buildTree",
    tests: [t("五个节点", "tree_values(buildTree([3,9,20,15,7], [9,3,15,20,7]))", [3,9,20,null,null,15,7]), t("单节点", "tree_values(buildTree([-1], [-1]))", [-1])] }),
  q({ id: 437, title: "路径总和 III", slug: "path-sum-iii", topic: "二叉树", difficulty: "中等",
    summary: "统计树中向下且节点和等于目标值的路径数量，路径可从任意节点开始。", example: "[10,5,-3,3,2,null,11,3,-2,null,1], target=8 → 3",
    method: "DFS 维护路径前缀和，用哈希表查询 current-target 出现次数。", params: ["root", "targetSum"],
    hint: "离开节点时要撤销当前前缀和计数。", complexity: "时间 O(n)，空间 O(h)", functionName: "pathSum",
    tests: [t("目标和 8", "pathSum(build_tree([10,5,-3,3,2,None,11,3,-2,None,1]), 8)", 3), t("目标和 22", "pathSum(build_tree([5,4,8,11,None,13,4,7,2,None,None,5,1]), 22)", 3)] }),
  q({ id: 236, title: "二叉树的最近公共祖先", slug: "lowest-common-ancestor-of-a-binary-tree", topic: "二叉树", difficulty: "中等",
    summary: "找出二叉树中两个指定节点最靠下的共同祖先。", example: "树 [3,5,1,6,2,0,8,null,null,7,4]，p=5,q=1 → 3",
    method: "递归在左右子树中寻找；若两边都找到，当前节点就是答案。", params: ["root", "p", "q"],
    hint: "当前节点等于 p 或 q 时直接向上返回。", complexity: "时间 O(n)，空间 O(h)", functionName: "lowestCommonAncestor",
    tests: [t("5 与 1", "lca_value(build_tree([3,5,1,6,2,0,8,None,None,7,4]), 5, 1, lowestCommonAncestor)", 3), t("5 与 4", "lca_value(build_tree([3,5,1,6,2,0,8,None,None,7,4]), 5, 4, lowestCommonAncestor)", 5)] }),
  q({ id: 124, title: "二叉树中的最大路径和", slug: "binary-tree-maximum-path-sum", topic: "二叉树", difficulty: "困难",
    summary: "求树中任意一条不重复节点路径的最大节点和。", example: "[-10,9,20,null,null,15,7] → 42",
    method: "后序计算向父节点能贡献的最大单支路径，并用左右贡献加根更新全局答案。", params: ["root"],
    hint: "负贡献应当按 0 处理；向上只能选择一侧。", complexity: "时间 O(n)，空间 O(h)", functionName: "maxPathSum",
    tests: [t("跨过节点 20", "maxPathSum(build_tree([-10,9,20,None,None,15,7]))", 42), t("两节点", "maxPathSum(build_tree([2,-1]))", 2)] }),
  q({ id: 200, title: "岛屿数量", slug: "number-of-islands", topic: "图论", difficulty: "中等",
    summary: "统计由上下左右相邻的陆地组成的岛屿数量。", example: "四行网格中有三块互不相连的陆地 → 3",
    method: "扫描网格，遇到未访问陆地就计数并 DFS/BFS 淹没整座岛。", params: ["grid"],
    hint: "每格最多访问一次，访问后可以直接改成水。", complexity: "时间 O(mn)，空间 O(mn)", functionName: "numIslands",
    tests: [t("一座大岛", "numIslands([list('11110'),list('11010'),list('11000'),list('00000')])", 1), t("三座岛", "numIslands([list('11000'),list('11000'),list('00100'),list('00011')])", 3)] }),
  q({ id: 994, title: "腐烂的橘子", slug: "rotting-oranges", topic: "图论", difficulty: "中等",
    summary: "腐烂橘子每分钟感染四邻新鲜橘子，求全部腐烂的最少分钟数。", example: "[[2,1,1],[1,1,0],[0,1,1]] → 4",
    method: "把所有腐烂橘子同时加入队列，做多源 BFS 分层扩散。", params: ["grid"],
    hint: "最后若仍有新鲜橘子，就返回 -1。", complexity: "时间 O(mn)，空间 O(mn)", functionName: "orangesRotting",
    tests: [t("四分钟扩散", "orangesRotting([[2,1,1],[1,1,0],[0,1,1]])", 4), t("有孤立橘子", "orangesRotting([[2,1,1],[0,1,1],[1,0,1]])", -1)] }),
  q({ id: 207, title: "课程表", slug: "course-schedule", topic: "图论", difficulty: "中等",
    summary: "根据课程先修关系，判断能否学完所有课程。", example: "2 门课，关系 [[1,0]] → true",
    method: "建立有向图并做拓扑排序，能弹出全部节点说明没有环。", params: ["numCourses", "prerequisites"],
    hint: "先把入度为 0 的课程加入队列。", complexity: "时间 O(V+E)，空间 O(V+E)", functionName: "canFinish",
    tests: [t("单向依赖", "canFinish(2, [[1,0]])", true), t("互相依赖", "canFinish(2, [[1,0],[0,1]])", false)] }),
  q({ id: 208, title: "实现 Trie（前缀树）", slug: "implement-trie-prefix-tree", topic: "图论", difficulty: "中等",
    summary: "实现单词插入、完整单词查询和前缀查询。", example: "插入 apple 后，search(apple)=true，startsWith(app)=true",
    method: "每个节点保存字符到子节点的映射，并用结束标记区分完整单词。", params: [],
    hint: "走完字符不代表单词存在，还要检查结束标记。", complexity: "每次操作 O(L)，空间 O(总字符数)",
    starterCode: `class Trie:
    def __init__(self):
        self.children = {}
        self.is_end = False

    def insert(self, word):
        pass

    def search(self, word):
        pass

    def startsWith(self, prefix):
        pass`,
    tests: [t("插入与前缀查询", "run_operations(Trie, ['Trie','insert','search','search','startsWith','insert','search'], [[],['apple'],['apple'],['app'],['app'],['app'],['app']])", [null,null,true,false,true,null,true])] }),
  q({ id: 46, title: "全排列", slug: "permutations", topic: "回溯", difficulty: "中等",
    summary: "返回无重复数组的所有可能排列。", example: "[1,2,3] → 6 种排列",
    method: "回溯选择尚未使用的数字，路径长度等于 n 时收集答案。", params: ["nums"],
    hint: "撤销选择是回溯不可缺少的一步。", complexity: "时间 O(n·n!)，空间 O(n)", functionName: "permute",
    tests: [t("三个数字", "sorted(permute([1,2,3]))", [[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]), t("单个数字", "permute([0])", [[0]])] }),
  q({ id: 78, title: "子集", slug: "subsets", topic: "回溯", difficulty: "中等",
    summary: "返回无重复数组的所有子集，包括空集。", example: "[1,2,3] → 8 个子集",
    method: "每到一个位置都可选择加入或跳过，或者用起点控制下一次选择。", params: ["nums"],
    hint: "每个回溯节点上的当前路径本身就是一个子集。", complexity: "时间 O(n·2ⁿ)，空间 O(n)", functionName: "subsets",
    tests: [t("三个数字", "sorted(subsets([1,2,3]))", [[],[1],[1,2],[1,2,3],[1,3],[2],[2,3],[3]]), t("单个数字", "sorted(subsets([0]))", [[],[0]])] }),
  q({ id: 17, title: "电话号码的字母组合", slug: "letter-combinations-of-a-phone-number", topic: "回溯", difficulty: "中等",
    summary: "根据手机九宫格映射，返回数字串可能代表的所有字母组合。", example: "23 → [ad,ae,af,bd,be,bf,cd,ce,cf]",
    method: "逐位枚举该数字对应的字母，递归构造字符串。", params: ["digits"],
    hint: "为空输入直接返回空列表。", complexity: "时间 O(4ⁿ)，空间 O(n)", functionName: "letterCombinations",
    tests: [t("数字 23", "letterCombinations('23')", ["ad","ae","af","bd","be","bf","cd","ce","cf"]), t("空字符串", "letterCombinations('')", [])] }),
  q({ id: 39, title: "组合总和", slug: "combination-sum", topic: "回溯", difficulty: "中等",
    summary: "从无重复候选数中选出和为 target 的组合，每个数可重复使用。", example: "candidates=[2,3,6,7], target=7 → [[2,2,3],[7]]",
    method: "从当前下标开始回溯；选择后仍从同一下标继续表示可重复。", params: ["candidates", "target"],
    hint: "排序后，当候选数超过剩余目标即可剪枝。", complexity: "取决于答案规模，递归深度 O(target/min)", functionName: "combinationSum",
    tests: [t("目标 7", "sorted([sorted(x) for x in combinationSum([2,3,6,7], 7)])", [[2,2,3],[7]]), t("目标 8", "sorted([sorted(x) for x in combinationSum([2,3,5], 8)])", [[2,2,2,2],[2,3,3],[3,5]])] }),
  q({ id: 22, title: "括号生成", slug: "generate-parentheses", topic: "回溯", difficulty: "中等",
    summary: "生成 n 对括号组成的全部有效字符串。", example: "n=3 → 5 种有效组合",
    method: "左括号未用完就可放；右括号已用数小于左括号时才可放。", params: ["n"],
    hint: "任何前缀中右括号数量都不能超过左括号。", complexity: "时间与第 n 个卡特兰数同阶，空间 O(n)", functionName: "generateParenthesis",
    tests: [t("三对括号", "sorted(generateParenthesis(3))", ["((()))","(()())","(())()","()(())","()()()"]), t("一对括号", "generateParenthesis(1)", ["()"]) ] }),
  q({ id: 79, title: "单词搜索", slug: "word-search", topic: "回溯", difficulty: "中等",
    summary: "判断能否从字符网格相邻格中依次拼出单词，每格最多使用一次。", example: "ABCE/SFCS/ADEE 中可找到 ABCCED",
    method: "从每个可能起点 DFS，匹配一格后临时标记已访问。", params: ["board", "word"],
    hint: "回退时恢复字符，供其他路径使用。", complexity: "最坏时间 O(mn·4ᴸ)，空间 O(L)", functionName: "exist",
    tests: [t("能找到 ABCCED", "exist([list('ABCE'),list('SFCS'),list('ADEE')], 'ABCCED')", true), t("不能重复使用格子", "exist([list('ABCE'),list('SFCS'),list('ADEE')], 'ABCB')", false)] }),
  q({ id: 131, title: "分割回文串", slug: "palindrome-partitioning", topic: "回溯", difficulty: "中等",
    summary: "把字符串切分成若干段，返回每段都是回文串的所有方案。", example: "aab → [[a,a,b],[aa,b]]",
    method: "枚举当前段的结束位置，仅当该段回文时继续递归。", params: ["s"],
    hint: "路径到达字符串末尾时收集答案。", complexity: "最坏时间 O(n·2ⁿ)，空间 O(n)", functionName: "partition",
    tests: [t("字符串 aab", "sorted(partition('aab'))", [["a","a","b"],["aa","b"]]), t("单字符", "partition('a')", [["a"]])] }),
  q({ id: 51, title: "N 皇后", slug: "n-queens", topic: "回溯", difficulty: "困难",
    summary: "在 n×n 棋盘放置 n 个皇后，使它们互不攻击。", example: "n=4 → 2 种布局",
    method: "逐行放皇后，用集合记录已占用列和两类对角线。", params: ["n"],
    hint: "同一主对角线 r-c 相同，副对角线 r+c 相同。", complexity: "时间约 O(n!)，空间 O(n)", functionName: "solveNQueens",
    tests: [t("四皇后方案数", "len(solveNQueens(4))", 2), t("一皇后", "solveNQueens(1)", [["Q"]])] }),
  q({ id: 35, title: "搜索插入位置", slug: "search-insert-position", topic: "二分查找", difficulty: "简单",
    summary: "在升序数组中返回目标下标；不存在时返回应插入的位置。", example: "[1,3,5,6], target=5 → 2",
    method: "二分寻找第一个大于等于 target 的位置。", params: ["nums", "target"],
    hint: "使用左闭右开区间时，循环结束的 left 就是答案。", complexity: "时间 O(log n)，空间 O(1)", functionName: "searchInsert",
    tests: [t("目标存在", "searchInsert([1,3,5,6], 5)", 2), t("插在中间", "searchInsert([1,3,5,6], 2)", 1)] }),
  q({ id: 74, title: "搜索二维矩阵", slug: "search-a-2d-matrix", topic: "二分查找", difficulty: "中等",
    summary: "在每行递增且下一行起点大于上一行终点的矩阵中找目标值。", example: "target=3 → true",
    method: "把矩阵看作长度 m·n 的一维升序数组做二分。", params: ["matrix", "target"],
    hint: "一维下标 i 对应 matrix[i//n][i%n]。", complexity: "时间 O(log(mn))，空间 O(1)", functionName: "searchMatrix",
    tests: [t("找到 3", "searchMatrix([[1,3,5,7],[10,11,16,20],[23,30,34,60]], 3)", true), t("找不到 13", "searchMatrix([[1,3,5,7],[10,11,16,20],[23,30,34,60]], 13)", false)] }),
  q({ id: 34, title: "在排序数组中查找元素的第一个和最后一个位置", slug: "find-first-and-last-position-of-element-in-sorted-array", topic: "二分查找", difficulty: "中等",
    summary: "返回目标值在升序数组中的起止下标，不存在则返回 [-1,-1]。", example: "[5,7,7,8,8,10], target=8 → [3,4]",
    method: "分别二分查找第一个 ≥ target 和第一个 > target 的位置。", params: ["nums", "target"],
    hint: "右端点可由 upper_bound(target)-1 得到。", complexity: "时间 O(log n)，空间 O(1)", functionName: "searchRange",
    tests: [t("目标出现两次", "searchRange([5,7,7,8,8,10], 8)", [3,4]), t("目标不存在", "searchRange([5,7,7,8,8,10], 6)", [-1,-1])] }),
  q({ id: 33, title: "搜索旋转排序数组", slug: "search-in-rotated-sorted-array", topic: "二分查找", difficulty: "中等",
    summary: "在无重复、经过旋转的升序数组中查找目标下标。", example: "[4,5,6,7,0,1,2], target=0 → 4",
    method: "每次二分至少有一半仍有序，判断目标是否落在该半区。", params: ["nums", "target"],
    hint: "先用 nums[left] 与 nums[mid] 判断哪一侧有序。", complexity: "时间 O(log n)，空间 O(1)", functionName: "search",
    tests: [t("找到 0", "search([4,5,6,7,0,1,2], 0)", 4), t("找不到 3", "search([4,5,6,7,0,1,2], 3)", -1)] }),
  q({ id: 153, title: "寻找旋转排序数组中的最小值", slug: "find-minimum-in-rotated-sorted-array", topic: "二分查找", difficulty: "中等",
    summary: "返回无重复旋转升序数组中的最小元素。", example: "[3,4,5,1,2] → 1",
    method: "比较中点与右端值；中点更大说明最小值在右侧，否则在含中点的左侧。", params: ["nums"],
    hint: "保留 mid 作为候选时令 right = mid。", complexity: "时间 O(log n)，空间 O(1)", functionName: "findMin",
    tests: [t("旋转三位", "findMin([3,4,5,1,2])", 1), t("未旋转", "findMin([11,13,15,17])", 11)] }),
  q({ id: 4, title: "寻找两个正序数组的中位数", slug: "median-of-two-sorted-arrays", topic: "二分查找", difficulty: "困难",
    summary: "在对数时间内求两个升序数组合并后的中位数。", example: "[1,3] 与 [2] → 2.0",
    method: "在较短数组上二分切分点，使左右两侧元素数量相等且边界有序。", params: ["nums1", "nums2"],
    hint: "短数组切 i 后，长数组切点 j 可由总左半长度确定。", complexity: "时间 O(log min(m,n))，空间 O(1)", functionName: "findMedianSortedArrays",
    tests: [t("总数为奇数", "findMedianSortedArrays([1,3], [2])", 2.0), t("总数为偶数", "findMedianSortedArrays([1,2], [3,4])", 2.5)] }),
  q({ id: 20, title: "有效的括号", slug: "valid-parentheses", topic: "栈", difficulty: "简单",
    summary: "判断括号字符串是否类型匹配且闭合顺序正确。", example: "()[]{} → true",
    method: "左括号入栈，右括号必须与栈顶配对。", params: ["s"],
    hint: "遇到右括号时栈为空也应立即失败。", complexity: "时间 O(n)，空间 O(n)", functionName: "isValid",
    tests: [t("三种括号", "isValid('()[]{}')", true), t("交叉闭合", "isValid('([)]')", false)] }),
  q({ id: 155, title: "最小栈", slug: "min-stack", topic: "栈", difficulty: "中等",
    summary: "实现支持 push、pop、top 和常数时间 getMin 的栈。", example: "压入 -2,0,-3 后 getMin()=-3",
    method: "另设最小值栈，或在每个元素旁保存入栈时的最小值。", params: [],
    hint: "弹出元素时，对应的历史最小值也要一起弹出。", complexity: "每次操作 O(1)，空间 O(n)",
    starterCode: `class MinStack:
    def __init__(self):
        self.stack = []

    def push(self, val):
        pass

    def pop(self):
        pass

    def top(self):
        pass

    def getMin(self):
        pass`,
    tests: [t("标准操作序列", "run_operations(MinStack, ['MinStack','push','push','push','getMin','pop','top','getMin'], [[],[-2],[0],[-3],[],[],[],[]])", [null,null,null,null,-3,null,0,-2])] }),
  q({ id: 394, title: "字符串解码", slug: "decode-string", topic: "栈", difficulty: "中等",
    summary: "解码形如 k[片段] 的字符串，括号可以嵌套。", example: "3[a2[c]] → accaccacc",
    method: "遇到 [ 时保存当前倍数和已构造字符串，遇到 ] 时弹栈拼接。", params: ["s"],
    hint: "数字可能有多位，要累积读取。", complexity: "时间 O(输出长度)，空间 O(嵌套深度+输出)", functionName: "decodeString",
    tests: [t("嵌套编码", "decodeString('3[a2[c]]')", "accaccacc"), t("两个片段", "decodeString('2[abc]3[cd]ef')", "abcabccdcdcdef")] }),
  q({ id: 739, title: "每日温度", slug: "daily-temperatures", topic: "栈", difficulty: "中等",
    summary: "对每天温度，返回还要等几天才会出现更高温度。", example: "[73,74,75,71,69,72,76,73] → [1,1,4,2,1,1,0,0]",
    method: "维护温度单调递减的下标栈，新高温会结算栈顶等待天数。", params: ["temperatures"],
    hint: "栈里保存下标，才能计算日期差。", complexity: "时间 O(n)，空间 O(n)", functionName: "dailyTemperatures",
    tests: [t("起伏温度", "dailyTemperatures([73,74,75,71,69,72,76,73])", [1,1,4,2,1,1,0,0]), t("持续下降", "dailyTemperatures([30,20,10])", [0,0,0])] }),
  q({ id: 84, title: "柱状图中最大的矩形", slug: "largest-rectangle-in-histogram", topic: "栈", difficulty: "困难",
    summary: "在柱状图中找出由连续柱子构成的最大矩形面积。", example: "[2,1,5,6,2,3] → 10",
    method: "维护高度递增栈，遇到更矮柱时弹出并计算被确定的宽度。", params: ["heights"],
    hint: "末尾加一个高度 0 的哨兵可结算剩余柱子。", complexity: "时间 O(n)，空间 O(n)", functionName: "largestRectangleArea",
    tests: [t("经典示例", "largestRectangleArea([2,1,5,6,2,3])", 10), t("两个柱子", "largestRectangleArea([2,4])", 4)] }),
  q({ id: 215, title: "数组中的第 K 个最大元素", slug: "kth-largest-element-in-an-array", topic: "堆", difficulty: "中等",
    summary: "返回未排序数组按大小排列后的第 k 大元素。", example: "[3,2,1,5,6,4], k=2 → 5",
    method: "维护大小为 k 的最小堆，或用快速选择只处理目标一侧。", params: ["nums", "k"],
    hint: "最小堆堆顶就是当前保留的第 k 大。", complexity: "堆法时间 O(n log k)，空间 O(k)", functionName: "findKthLargest",
    tests: [t("第 2 大", "findKthLargest([3,2,1,5,6,4], 2)", 5), t("含重复值", "findKthLargest([3,2,3,1,2,4,5,5,6], 4)", 4)] }),
  q({ id: 347, title: "前 K 个高频元素", slug: "top-k-frequent-elements", topic: "堆", difficulty: "中等",
    summary: "返回数组中出现频率最高的 k 个元素。", example: "[1,1,1,2,2,3], k=2 → [1,2]",
    method: "先计数，再用大小为 k 的最小堆或频率桶取答案。", params: ["nums", "k"],
    hint: "答案顺序不重要，测试时可排序。", complexity: "堆法时间 O(n log k)，空间 O(n)", functionName: "topKFrequent",
    tests: [t("前两个高频", "sorted(topKFrequent([1,1,1,2,2,3], 2))", [1,2]), t("只有一个元素", "topKFrequent([1], 1)", [1])] }),
  q({ id: 295, title: "数据流的中位数", slug: "find-median-from-data-stream", topic: "堆", difficulty: "困难",
    summary: "持续接收整数，并能随时返回当前所有数字的中位数。", example: "加入 1、2 后中位数 1.5，再加入 3 后为 2",
    method: "最大堆保存较小一半，最小堆保存较大一半，并始终保持大小平衡。", params: [],
    hint: "Python 可用负数模拟最大堆。", complexity: "addNum O(log n)，findMedian O(1)，空间 O(n)",
    starterCode: `class MedianFinder:
    def __init__(self):
        self.small = []  # 最大堆（存负数）
        self.large = []  # 最小堆

    def addNum(self, num):
        pass

    def findMedian(self):
        pass`,
    tests: [t("依次加入 1、2、3", "run_operations(MedianFinder, ['MedianFinder','addNum','addNum','findMedian','addNum','findMedian'], [[],[1],[2],[],[3],[]])", [null,null,null,1.5,null,2.0])] }),
  q({ id: 121, title: "买卖股票的最佳时机", slug: "best-time-to-buy-and-sell-stock", topic: "贪心", difficulty: "简单",
    summary: "只允许一次买入和一次卖出，求能获得的最大利润。", example: "[7,1,5,3,6,4] → 5",
    method: "从左到右维护历史最低价，并用当前价更新最大利润。", params: ["prices"],
    hint: "卖出必须发生在买入之后。", complexity: "时间 O(n)，空间 O(1)", functionName: "maxProfit",
    tests: [t("低买高卖", "maxProfit([7,1,5,3,6,4])", 5), t("持续下跌", "maxProfit([7,6,4,3,1])", 0)] }),
  q({ id: 55, title: "跳跃游戏", slug: "jump-game", topic: "贪心", difficulty: "中等",
    summary: "每格数字表示最大跳跃长度，判断能否从起点到达最后一格。", example: "[2,3,1,1,4] → true",
    method: "扫描时维护当前能到达的最远位置。", params: ["nums"],
    hint: "若当前下标已经超过最远可达位置，就无法继续。", complexity: "时间 O(n)，空间 O(1)", functionName: "canJump",
    tests: [t("可以到达", "canJump([2,3,1,1,4])", true), t("被 0 挡住", "canJump([3,2,1,0,4])", false)] }),
  q({ id: 45, title: "跳跃游戏 II", slug: "jump-game-ii", topic: "贪心", difficulty: "中等",
    summary: "保证能到终点，求从起点到最后一格的最少跳跃次数。", example: "[2,3,1,1,4] → 2",
    method: "在当前跳跃覆盖区间内寻找下一跳能达到的最远位置。", params: ["nums"],
    hint: "走到当前区间末端时，才真正增加一次跳跃。", complexity: "时间 O(n)，空间 O(1)", functionName: "jump",
    tests: [t("两次到达", "jump([2,3,1,1,4])", 2), t("首跳仍为 2", "jump([2,3,0,1,4])", 2)] }),
  q({ id: 763, title: "划分字母区间", slug: "partition-labels", topic: "贪心", difficulty: "中等",
    summary: "把字符串分成尽量多段，使每个字母最多出现在一个片段中。", example: "ababcbacadefegdehijhklij → [9,7,8]",
    method: "先记录每个字符最后位置，扫描时扩展当前片段的最远边界。", params: ["s"],
    hint: "下标到达当前边界时就可以切一段。", complexity: "时间 O(n)，空间 O(字符集)", functionName: "partitionLabels",
    tests: [t("三个片段", "partitionLabels('ababcbacadefegdehijhklij')", [9,7,8]), t("一个片段", "partitionLabels('eccbbbbdec')", [10])] }),
  q({ id: 70, title: "爬楼梯", slug: "climbing-stairs", topic: "动态规划", difficulty: "简单",
    summary: "每次爬 1 或 2 阶，求到达第 n 阶的不同方法数。", example: "n=3 → 3",
    method: "到第 i 阶的方法数等于前一阶与前两阶之和。", params: ["n"],
    hint: "这就是从初始值 1、2 开始的斐波那契型递推。", complexity: "时间 O(n)，空间 O(1)", functionName: "climbStairs",
    tests: [t("三阶", "climbStairs(3)", 3), t("五阶", "climbStairs(5)", 8)] }),
  q({ id: 118, title: "杨辉三角", slug: "pascals-triangle", topic: "动态规划", difficulty: "简单",
    summary: "生成杨辉三角的前 numRows 行。", example: "numRows=5 → 最后一行 [1,4,6,4,1]",
    method: "每行首尾为 1，中间值来自上一行相邻两数之和。", params: ["numRows"],
    hint: "第 i 行有 i+1 个元素。", complexity: "时间 O(n²)，空间 O(n²)（结果）", functionName: "generate",
    tests: [t("五行", "generate(5)", [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]]), t("一行", "generate(1)", [[1]])] }),
  q({ id: 198, title: "打家劫舍", slug: "house-robber", topic: "动态规划", difficulty: "中等",
    summary: "不能偷相邻房屋，求能偷到的最大金额。", example: "[2,7,9,3,1] → 12",
    method: "每间房选择偷（前前状态+当前值）或不偷（前一状态）。", params: ["nums"],
    hint: "只需保留前两个状态。", complexity: "时间 O(n)，空间 O(1)", functionName: "rob",
    tests: [t("五间房", "rob([2,7,9,3,1])", 12), t("四间房", "rob([1,2,3,1])", 4)] }),
  q({ id: 279, title: "完全平方数", slug: "perfect-squares", topic: "动态规划", difficulty: "中等",
    summary: "求和为 n 所需的最少完全平方数个数。", example: "n=12 → 3（4+4+4）",
    method: "完全背包：dp[i] 由所有不超过 i 的平方数转移。", params: ["n"],
    hint: "初始化 dp[0]=0，其余为无穷大。", complexity: "时间 O(n√n)，空间 O(n)", functionName: "numSquares",
    tests: [t("12", "numSquares(12)", 3), t("13", "numSquares(13)", 2)] }),
  q({ id: 322, title: "零钱兑换", slug: "coin-change", topic: "动态规划", difficulty: "中等",
    summary: "用给定面额凑出 amount，返回最少硬币数；无法凑出则返回 -1。", example: "coins=[1,2,5], amount=11 → 3",
    method: "完全背包：对每个金额尝试最后使用每种硬币。", params: ["coins", "amount"],
    hint: "dp[x] 表示凑出金额 x 的最少硬币数。", complexity: "时间 O(amount·coins)，空间 O(amount)", functionName: "coinChange",
    tests: [t("11 元", "coinChange([1,2,5], 11)", 3), t("无法凑出", "coinChange([2], 3)", -1)] }),
  q({ id: 139, title: "单词拆分", slug: "word-break", topic: "动态规划", difficulty: "中等",
    summary: "判断字符串能否由词典中的单词连续拼接而成，单词可重复使用。", example: "leetcode + [leet,code] → true",
    method: "dp[i] 表示前 i 个字符可拆分，枚举最后一个单词的起点。", params: ["s", "wordDict"],
    hint: "初始空前缀 dp[0] 必须为 true。", complexity: "时间 O(n²)，空间 O(n)", functionName: "wordBreak",
    tests: [t("可拆成两个词", "wordBreak('leetcode', ['leet','code'])", true), t("无法完整拆分", "wordBreak('catsandog', ['cats','dog','sand','and','cat'])", false)] }),
  q({ id: 300, title: "最长递增子序列", slug: "longest-increasing-subsequence", topic: "动态规划", difficulty: "中等",
    summary: "求严格递增但不要求连续的最长子序列长度。", example: "[10,9,2,5,3,7,101,18] → 4",
    method: "维护每种长度递增序列的最小结尾，并用二分替换。", params: ["nums"],
    hint: "更小的结尾给后续数字留下更大空间。", complexity: "时间 O(n log n)，空间 O(n)", functionName: "lengthOfLIS",
    tests: [t("经典示例", "lengthOfLIS([10,9,2,5,3,7,101,18])", 4), t("含重复", "lengthOfLIS([0,1,0,3,2,3])", 4)] }),
  q({ id: 152, title: "乘积最大子数组", slug: "maximum-product-subarray", topic: "动态规划", difficulty: "中等",
    summary: "找出乘积最大的非空连续子数组并返回乘积。", example: "[2,3,-2,4] → 6",
    method: "同时维护以当前位置结尾的最大和最小乘积，负数会交换两者角色。", params: ["nums"],
    hint: "最小负积乘负数可能变成最大正积。", complexity: "时间 O(n)，空间 O(1)", functionName: "maxProduct",
    tests: [t("正积最大", "maxProduct([2,3,-2,4])", 6), t("被零分隔", "maxProduct([-2,0,-1])", 0)] }),
  q({ id: 416, title: "分割等和子集", slug: "partition-equal-subset-sum", topic: "动态规划", difficulty: "中等",
    summary: "判断数组能否分成元素和相等的两个子集。", example: "[1,5,11,5] → true",
    method: "总和为偶数时，转化为容量 sum/2 的 0-1 背包。", params: ["nums"],
    hint: "一维布尔 dp 要从大容量向小容量更新。", complexity: "时间 O(n·sum)，空间 O(sum)", functionName: "canPartition",
    tests: [t("可以平分", "canPartition([1,5,11,5])", true), t("无法平分", "canPartition([1,2,3,5])", false)] }),
  q({ id: 32, title: "最长有效括号", slug: "longest-valid-parentheses", topic: "动态规划", difficulty: "困难",
    summary: "求括号字符串中最长连续有效片段的长度。", example: ")()()) → 4",
    method: "用栈保存未匹配下标与最近无效边界，或用 dp 连接前一段有效括号。", params: ["s"],
    hint: "栈底保留最后一个无法匹配的右括号下标。", complexity: "时间 O(n)，空间 O(n)", functionName: "longestValidParentheses",
    tests: [t("中间有效", "longestValidParentheses(')()())')", 4), t("前缀未闭合", "longestValidParentheses('(()')", 2)] }),
  q({ id: 62, title: "不同路径", slug: "unique-paths", topic: "动态规划", difficulty: "中等",
    summary: "机器人只能向右或向下，求从网格左上到右下的路径数。", example: "m=3, n=7 → 28",
    method: "到达每格的路径数等于上方与左方路径数之和。", params: ["m", "n"],
    hint: "第一行和第一列都只有一种走法。", complexity: "时间 O(mn)，空间 O(n)", functionName: "uniquePaths",
    tests: [t("3×7", "uniquePaths(3, 7)", 28), t("3×2", "uniquePaths(3, 2)", 3)] }),
  q({ id: 64, title: "最小路径和", slug: "minimum-path-sum", topic: "动态规划", difficulty: "中等",
    summary: "只能向右或向下，求从网格左上到右下经过数字的最小总和。", example: "[[1,3,1],[1,5,1],[4,2,1]] → 7",
    method: "每格最优值等于当前数字加上上方与左方较小值。", params: ["grid"],
    hint: "可直接在原网格或一维数组上累计。", complexity: "时间 O(mn)，空间 O(n)", functionName: "minPathSum",
    tests: [t("3×3", "minPathSum([[1,3,1],[1,5,1],[4,2,1]])", 7), t("2×3", "minPathSum([[1,2,3],[4,5,6]])", 12)] }),
  q({ id: 5, title: "最长回文子串", slug: "longest-palindromic-substring", topic: "动态规划", difficulty: "中等",
    summary: "返回字符串中最长的连续回文子串。", example: "babad → bab 或 aba",
    method: "枚举每个字符和字符间隙作为中心，向两侧扩展。", params: ["s"],
    hint: "奇数长度和偶数长度需要两种中心。", complexity: "时间 O(n²)，空间 O(1)", functionName: "longestPalindrome",
    tests: [t("两个等长答案", "longestPalindrome('babad') in ['bab','aba']", true), t("偶数回文", "longestPalindrome('cbbd')", "bb")] }),
  q({ id: 1143, title: "最长公共子序列", slug: "longest-common-subsequence", topic: "动态规划", difficulty: "中等",
    summary: "求两个字符串共有的最长子序列长度，字符不必连续。", example: "abcde 与 ace → 3",
    method: "字符相等时接上左上状态；不等时取上方和左方较大值。", params: ["text1", "text2"],
    hint: "dp[i][j] 表示两个前缀的答案。", complexity: "时间 O(mn)，空间 O(n)", functionName: "longestCommonSubsequence",
    tests: [t("公共序列 ace", "longestCommonSubsequence('abcde', 'ace')", 3), t("没有公共字符", "longestCommonSubsequence('abc', 'def')", 0)] }),
  q({ id: 72, title: "编辑距离", slug: "edit-distance", topic: "动态规划", difficulty: "中等",
    summary: "求把一个单词变成另一个单词所需的最少插入、删除或替换次数。", example: "horse → ros 需要 3 步",
    method: "二维 DP 比较两个前缀；末字符不同则从三种操作的前态取最小值加一。", params: ["word1", "word2"],
    hint: "空串变长度 j 的字符串需要 j 次插入。", complexity: "时间 O(mn)，空间 O(n)", functionName: "minDistance",
    tests: [t("horse 到 ros", "minDistance('horse', 'ros')", 3), t("intention 到 execution", "minDistance('intention', 'execution')", 5)] }),
  q({ id: 136, title: "只出现一次的数字", slug: "single-number", topic: "技巧", difficulty: "简单",
    summary: "除一个数字只出现一次外，其余都出现两次，找出单独的数字。", example: "[4,1,2,1,2] → 4",
    method: "把所有数字异或；相同数字抵消，0 与任何数异或仍是该数。", params: ["nums"],
    hint: "异或满足交换律和结合律。", complexity: "时间 O(n)，空间 O(1)", functionName: "singleNumber",
    tests: [t("单独数字 4", "singleNumber([4,1,2,1,2])", 4), t("单独数字 1", "singleNumber([2,2,1])", 1)] }),
  q({ id: 169, title: "多数元素", slug: "majority-element", topic: "技巧", difficulty: "简单",
    summary: "找出数组中出现次数超过一半的元素。", example: "[2,2,1,1,1,2,2] → 2",
    method: "Boyer-Moore 投票：相同加票，不同抵消，票数归零时换候选。", params: ["nums"],
    hint: "多数元素最终不可能被其他元素完全抵消。", complexity: "时间 O(n)，空间 O(1)", functionName: "majorityElement",
    tests: [t("多数为 2", "majorityElement([2,2,1,1,1,2,2])", 2), t("多数为 3", "majorityElement([3,2,3])", 3)] }),
  q({ id: 75, title: "颜色分类", slug: "sort-colors", topic: "技巧", difficulty: "中等",
    summary: "原地把只含 0、1、2 的数组按颜色顺序排列。", example: "[2,0,2,1,1,0] → [0,0,1,1,2,2]",
    method: "荷兰国旗三指针：0 放左侧，2 放右侧，1 留中间。", params: ["nums"],
    hint: "从右边换回的元素尚未检查，当前指针不要立刻前进。", complexity: "时间 O(n)，空间 O(1)", functionName: "sortColors",
    tests: [t("六个颜色", "mutated([2,0,2,1,1,0], sortColors)", [0,0,1,1,2,2]), t("三个颜色", "mutated([2,0,1], sortColors)", [0,1,2])] }),
  q({ id: 31, title: "下一个排列", slug: "next-permutation", topic: "技巧", difficulty: "中等",
    summary: "原地改成字典序中的下一个更大排列；若已最大则变最小。", example: "[1,2,3] → [1,3,2]",
    method: "从右找第一个下降点，与右侧刚好更大的数交换，再反转后缀。", params: ["nums"],
    hint: "下降点右侧本来是非递增序列。", complexity: "时间 O(n)，空间 O(1)", functionName: "nextPermutation",
    tests: [t("普通情况", "mutated([1,2,3], nextPermutation)", [1,3,2]), t("最大排列回到最小", "mutated([3,2,1], nextPermutation)", [1,2,3])] }),
  q({ id: 287, title: "寻找重复数", slug: "find-the-duplicate-number", topic: "技巧", difficulty: "中等",
    summary: "长度 n+1 的数组只含 1..n，在不修改数组且常数空间下找重复数。", example: "[1,3,4,2,2] → 2",
    method: "把下标到 nums[index] 看作链表，用快慢指针寻找环入口。", params: ["nums"],
    hint: "重复值对应两条边指向同一节点，因此形成环。", complexity: "时间 O(n)，空间 O(1)", functionName: "findDuplicate",
    tests: [t("重复 2", "findDuplicate([1,3,4,2,2])", 2), t("重复 3", "findDuplicate([3,1,3,4,2])", 3)] }),
];

if (problems.length !== 101) {
  throw new Error(`Hot 100 加练题数据应为 101 题，当前为 ${problems.length} 题`);
}

export const officialProblemUrl = (problem: Pick<Problem, "slug">): string =>
  `https://leetcode.cn/problems/${problem.slug}/`;

export default problems;
